builders:
  dummy_extension_generators:
    import: "package:withers_extension/withers_extension.dart"
    builder_factories: ["withersDummyBuilder"]
    build_extensions: {".dart": []}
    auto_apply: dependents
