name: withers_extension
version: 0.4.2
author: svarzee <svarzee@gmail.com>
homepage: https://github.com/svarzee/withers_extension
description: >-
  Uses class_extensions to generate withers.
  Withers are a convenient way of constructing copies of immutable objects with altered values.
environment:
  sdk: '>=2.3.0 <3.0.0'

dependencies:
  class_extensions: ^0.2.0
  withers_extension_annotations: ^0.0.0
  analyzer: '>=0.37.1 <0.39.0'
  build: '>=0.12.6 <2.0.0'
  source_gen: ^0.9.0

dev_dependencies:
  build_runner: ^1.0.0
