name: example

dependencies:
  class_extensions_annotations: ^0.0.0
  withers_extension_annotations: ^0.0.0

dev_dependencies:
  build_runner: ^1.0.0
  class_extensions: ^0.2.0
  withers_extension: ^0.4.0
