name: example

dependencies:
  class_extensions_annotations: ^0.1.0
  withers_extension_annotations: ^0.1.0

dev_dependencies:
  build_runner: ^1.0.0
  class_extensions: ^0.7.0
  withers_extension: ^0.6.0
